create table WORK_ITEM (
    ID IDENTITY,
    WORK_ITEM_IDENTIFIER CHARACTER (255),
    MAIL_TO CHARACTER (255)
);

create table OUTBOUND_EMAIL (
    ID IDENTITY,
    OUTBOUND_EMAIL_IDENTIFIER CHARACTER (255),
    MAIL_TO CHARACTER (255),
    MAIL_FROM CHARACTER (255),
    SENT TIMESTAMP
);